-- NOT KEYWORD
SELECT *
FROM CUSTOMERS
WHERE BIRTH_DATE > '1990-01-01' OR 
	POINTS> 1000 AND 
    NOT STATE = 'VA';  -- AND OPERATOR IS EVALUATED FIRST
SELECT * 
FROM CUSTOMERS
WHERE NOT(BIRTH_DATE > '1990-01-01' OR 
	POINTS> 1000 AND 
    STATE = 'VA');
